<a href="https://colab.research.google.com/github/sharukshaik07/test/blob/main/wine_quality_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [ ]:
data = pd.read_csv("/content/drive/MyDrive/winequality-red.csv")
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [ ]:
# train_set = 1000 , test_set = 599
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
data['quality'].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
tr_set,ts_set = train_test_split(data,test_size=599,random_state=42)
tr_set

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
1530            6.6             0.440         0.09  ...       0.69     11.3        6
782             9.0             0.820         0.05  ...       0.53     10.0        5
164             7.3             0.590         0.26  ...       0.49      9.4        5
290             8.7             0.520         0.09  ...       0.86     10.6        7
1510            6.4             0.360         0.21  ...       0.77      9.7        6
...             ...               ...          ...  ...        ...      ...      ...
1130            9.1             0.600         0.00  ...       0.63     10.4        6
1294            8.2             0.635         0.10  ...       0.75     10.9        6
860             7.2             0.620         0.06  ...       0.54      9.5        5
1459            7.9             0.200         0.35  ...       0.80     11.9        7
1126            5.8             0.290         0.26  ...       0.54     13.5        6

[1000 rows x 12 columns]

In [ ]:
x_train = tr_set.drop('quality',1)
y_train = tr_set['quality'].copy()
x_test = ts_set.drop('quality',1)
y_test = ts_set['quality'].copy()
y_t = ts_set[['quality']]
y_t

quality
803         6
124         5
350         6
682         5
1326        6
...       ...
41          4
131         5
1182        6
1548        5
741         5

[599 rows x 1 columns]

In [ ]:
x_train.values

array([[ 6.6 ,  0.44,  0.09, ...,  3.42,  0.69, 11.3 ],
       [ 9.  ,  0.82,  0.05, ...,  3.36,  0.53, 10.  ],
       [ 7.3 ,  0.59,  0.26, ...,  3.37,  0.49,  9.4 ],
       ...,
       [ 7.2 ,  0.62,  0.06, ...,  3.51,  0.54,  9.5 ],
       [ 7.9 ,  0.2 ,  0.35, ...,  3.32,  0.8 , 11.9 ],
       [ 5.8 ,  0.29,  0.26, ...,  3.39,  0.54, 13.5 ]])

In [ ]:
#statistical method
x = np.c_[np.ones(len(x_train)),x_train.values]
x


array([[ 1.  ,  6.6 ,  0.44, ...,  3.42,  0.69, 11.3 ],
       [ 1.  ,  9.  ,  0.82, ...,  3.36,  0.53, 10.  ],
       [ 1.  ,  7.3 ,  0.59, ...,  3.37,  0.49,  9.4 ],
       ...,
       [ 1.  ,  7.2 ,  0.62, ...,  3.51,  0.54,  9.5 ],
       [ 1.  ,  7.9 ,  0.2 , ...,  3.32,  0.8 , 11.9 ],
       [ 1.  ,  5.8 ,  0.29, ...,  3.39,  0.54, 13.5 ]])

In [ ]:
y = y_t.values
y[ :4]

array([[6],
       [5],
       [6],
       [5]])

In [ ]:
from numpy.linalg import inv
theta = inv(x.T.dot(x)).dot(x.T.dot(y_train)) 

theta

array([ 2.27588012e+01,  2.47282338e-02, -1.14743567e+00, -2.75960844e-01,
        1.96928312e-02, -1.80730851e+00,  2.96220387e-03, -2.89591393e-03,
       -1.90482751e+01, -2.96497614e-01,  7.56549394e-01,  2.89426618e-01])

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
ycap = lr.predict(x_train)
ycap

In [ ]:
from sklearn.metrics import mean_squared_error,r2_score
print("mse:",mean_squared_error(y_train,ycap))
print("accuracy:",r2_score(y_train,ycap))

mse: 0.41673786158888165
accuracy: 0.3613956664221767


In [ ]:
print("intercept:",lr.intercept_)
print("slopes:",lr.coef_)

intercept: 22.7588011782069
slopes: [ 2.47282338e-02 -1.14743567e+00 -2.75960844e-01  1.96928312e-02
 -1.80730851e+00  2.96220387e-03 -2.89591393e-03 -1.90482751e+01
 -2.96497614e-01  7.56549394e-01  2.89426618e-01]


In [ ]:
# or 
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression(fit_intercept=False)
lin